version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ch-angular-app:${APP_VERSION}
    container_name: angular-frontend
    environment:
      - API_URL=${API_URL}
    ports:
      - "${APP_PORT}:80"
    restart: always
